// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "HomePage": {
      "title": "Hello world!",
      "description": "This is a basic example that demonstrates the usage of <code>next-intl</code> with the Next.js App Router. Try changing the locale in the top right corner and see how the content changes."
    },
    "LocaleLayout": {
      "title": "next-intl example"
    },
    "PageLayout": {
      "links": {
        "docs": {
          "description": "Learn more about next-intl in the official docs.",
          "href": "https://next-intl.dev",
          "title": "Docs"
        },
        "source": {
          "description": "Browse the source code of this example on GitHub.",
          "href": "https://github.com/amannn/next-intl/tree/main/examples/example-app-router",
          "title": "Source code"
        }
      }
    },
    "LocaleSwitcher": {
      "label": "Change language",
      "locale": "{locale, select, de {🇩🇪 Deutsch} en {🇺🇸 English} other {Unknown}}"
    },
    "IndexPage": {
    "description": "This is a basic example that demonstrates the usage of <code>next-intl</code> with the Next.js App Router. Try changing the locale in the top right corner and see how the content changes.",
    "title": "next-intl example"
    }
  };
export default messages;